name: FAX
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.9.0
  - torchvision=0.10.0
  - cudatoolkit=11.1
  - click==8.0.3
  - einops==0.4.0
  - matplotlib==3.5.1
  - networkx==2.6.3
  - numpy==1.22.0
  - pandas==1.3.5
  - plotly==5.9.0
  - scipy==1.7.3
  - tqdm==4.62.3
  - notebook
  - ipywidgets
  - pip
  - pip:
    - gdown
    - pyyaml
    - Pillow==9.2.0
    - progressbar33==2.4
    - geomstats==2.4.2
    - opencv-python==4.7.0.72
    - scikit_learn==1.1.2